# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: bun
    directory: '/'
    schedule:
      interval: daily
      time: '04:00'
      timezone: Europe/Berlin
    open-pull-requests-limit: 10
    versioning-strategy: auto
    labels:
      - 'dependencies'
    groups:
      astro:
        patterns:
          - 'astro'
          - '@astrojs/*'
      tailwindcss:
        patterns:
          - 'tailwindcss'
          - '@tailwindcss/*'
      prettier:
        patterns:
          - 'prettier'
          - 'prettier-plugin-*'
      icons:
        patterns:
          - 'astro-icon'
          - '@iconify-json/*'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
      time: '04:00'
      timezone: Europe/Berlin
    labels:
      - 'dependencies'
