image: ghcr.io/solectrus/solectrus:latest
depends_on:
  db:
    condition: service_healthy
  influxdb:
    condition: service_healthy
  redis:
    condition: service_healthy
links:
  - db
  - influxdb
  - redis
ports:
  - 3000:3000
environment:
  - APP_HOST
  - FORCE_SSL
  - SECRET_KEY_BASE
  - INSTALLATION_DATE
  - ADMIN_PASSWORD
  - FRAME_ANCESTORS
  - DB_HOST=db
  - DB_PASSWORD=${POSTGRES_PASSWORD}
  - DB_USER=postgres
  - REDIS_URL=redis://redis:6379/1
  - INFLUX_HOST
  - INFLUX_TOKEN=${INFLUX_TOKEN_READ}
  - INFLUX_ORG
  - INFLUX_BUCKET
  - INFLUX_MEASUREMENT_PV
  - INFLUX_MEASUREMENT_FORECAST
  - INFLUX_POLL_INTERVAL
  - WEB_CONCURRENCY
healthcheck:
  test: ['CMD-SHELL', 'nc -z 127.0.0.1 3000 || exit 1']
restart: always
logging:
  options:
    max-size: '10m'
    max-file: '3'
