image: traefik:v2.11
environment:
  - TZ
command:
  - '--providers.docker=true'
  - '--providers.docker.exposedbydefault=false'
  - '--entrypoints.web.address=:80'
  - '--entrypoints.websecure.address=:443'
  - '--entrypoints.influxdb.address=:8086'
  - '--certificatesresolvers.myresolver.acme.tlschallenge=true'
  - '--certificatesresolvers.myresolver.acme.email=${LETSENCRYPT_EMAIL}'
  - '--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json'
ports:
  - '80:80'
  - '443:443'
  - '8086:8086'
volumes:
  - ${TRAEFIK_VOLUME_PATH}:/letsencrypt
  - '/var/run/docker.sock:/var/run/docker.sock:ro'
restart: unless-stopped
