name: Test, build, and deploy to ghcr.io

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          cache: yarn

      - run: yarn install

      - run: yarn tsc

      - run: yarn vitest run

      - name: Install Nginx
        run: sudo apt-get update && sudo apt-get install -y nginx

      - name: Copy Nginx config to default location
        run: sudo cp -r ./_nginx /etc/nginx

      - name: Test Nginx configuration
        run: sudo nginx -t

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          cache: yarn

      - run: yarn install

      - run: yarn build

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/setup-buildx-action@v3

      - uses: docker/build-push-action@v6
        with:
          push: ${{ github.event_name == 'push' }}
          provenance: false
          tags: ghcr.io/solectrus/configurator:latest
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
          labels: |
            org.opencontainers.image.title=${{ github.event.repository.name }}
            org.opencontainers.image.description=${{ github.event.repository.description }}
            org.opencontainers.image.url=${{ github.event.repository.html_url }}
            org.opencontainers.image.revision=${{ github.sha }}

      - name: Deploy
        env:
          DEPLOY_HOOK: ${{ secrets.DEPLOY_HOOK }}
        if: github.ref == 'refs/heads/main' && env.DEPLOY_HOOK != null
        run: curl -X POST ${{ secrets.DEPLOY_HOOK }}
